server:
  port: 8080
  servlet: 
    encoding:
      charset: utf-8
      force: true
      

spring: 
  mvc:
    view: 
      prefix: /WEB-INF/view
      suffix: .jsp
  datasource: # DB 설정
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  sql: 
    init: 
      schema-locations:
      - classpath:db/table.sql # 콜론 띄어쓰기 ㄴㄴ db 폴더 아래 table.sql 파일 읽으라는 뜻
      data-locations:
      - classpath:db/data.sql
  h2: 
    console: 
      enabled: true
  output: 
    ansi: # 쿼리문 표준
      enabled: always